name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      uses: github/codeql-action/upload-sarif@v2
  with:
    sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth:     
  name: 'Qodana Scan'
  uses: JetBrains/qodana-action@main
  env:
    QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        uses: JetBrains/qodana-action@v2022.3.4
